# Generated by Django 4.0.6 on 2022-08-26 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1500)),
                ('stack_trace', models.CharField(max_length=6150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
