version: "3.9"
services:      
  pgdb:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test_clean_architecture_django
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.xyz"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8080:80"
    depends_on:
      - pgdb
  api:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    volumes:
      - ./src:/code
